In [1]:
## simple calculator

In [4]:
x = 9;y=10



In [ ]:
print(x, y)

In [ ]:
add_result=x+y
sub_result=x-y
print(add_result,sub_result)

In [ ]:
print(f"the result of addition is {add_result} hello")

In [ ]:
print(f"the name is my property{add_result}")

In [10]:
a=20
b=10
result=(a==b)

In [ ]:
a==b

In [ ]:
result

In [27]:
age = 20
if age < 20:
    print("age")

In [ ]:
age=204
if age<20:
    print("my name is taruna")
else:
    print("you are ok")    

In [ ]:
year=(input("year"))
if year==year :
    print("this is an leap year")
    if year/2 :
        print("this is a multiple of 2")
    else: 
        print("not divisible by 2")
else:
    print("this is not an leap year")        


In [ ]:
for i in range(1,5):
    print(i)

In [ ]:
range(1,10)
print(range)

In [ ]:
for i in range(2,10,2):
    print(i)

In [ ]:
str="taruna rohilla"
for i in str:
    print(i)

In [ ]:
for i in range(20,10,-1):
    print(i)


In [13]:
count=0
while count<5:
    print(count)
    count=count+1

0
1
2
3
4


In [14]:
for i in range(19):
    if i==5:
        break
    print(i)

0
1
2
3
4


In [18]:
for i in range(3):
    for j in range(2):
        print(f"i:{i}and j:{j}")

i:0and j:0
i:0and j:1
i:1and j:0
i:1and j:1
i:2and j:0
i:2and j:1


In [19]:
n=10
sum=0
count=1
while count<=10:
    sum=sum+count
    count=count+1
print("sum of first 10 natural number:",sum)    

sum of first 10 natural number: 55


In [20]:
n=10
sum=0
for i in range(10):
    sum=sum+i
print(sum)    

45


In [ ]:
for num in range(1,101):
    if num>1:
        for i in range(2,num)
        if num 

In [23]:
## manage to do list
to_do_list=["buy groceries","clean the house","pay bills"]
to_do_list.append("meeting")
to_do_list.append("go to run")
to_do_list.remove("clean the house")
if"pay bills" in to_do_list:
    print("dont pay bills")
print("to do list")
for task in to_do_list:
    print(f"{task}")

  

dont pay bills
to do list
buy groceries
pay bills
meeting
go to run


In [27]:
inventory=["apple","orange","grapes"]
item=input("name of the item")
if item in inventory:
    print(f"{item}are in stock")
else:
    print(f"{item}out of stock") 
for item in inventory:
    print(f"{item}")    


apple,grapes,orangeout of stock
apple
orange
grapes


In [28]:
##creat a set
my_set={1,2,3,4,5}
print(type(my_set))

<class 'set'>


In [29]:
print(my_set)

{1, 2, 3, 4, 5}


In [34]:
num=20
if num>30 :
    print("number is positive")

else:
    print("no is not positive")
    if num % 2 == 0:
        print("even")
    else:
        print("odd")

 


no is not positive
even


In [36]:
x=20;y=30
print(x,y)

20 30


In [38]:
num=30
if num>20:
    print(num)

30


In [33]:
set1={1,2,3,4}
set1.add(7)
print(set1)

{1, 2, 3, 4, 7}


In [4]:
inventory=[1,2,3,4]
inventory.remove(3)
print(inventory)

[1, 2, 4]


In [6]:
set.clear()
print(set)

set()


In [7]:
set1={1,2,3,4}
set2={5,6,7,3}
union_set=set.union(set2)
print(union_set)

{1, 2, 3, 4, 5, 6, 7}


In [8]:
intersection=set1.intersection(set2)
print(intersection)

{3}


In [10]:
set1.intersection_update(set2)
print(set1)

{3}


In [16]:
set2.symmetric_difference(set1)
print(set2.symmetric_difference(set1))

{5, 6, 7}


In [20]:
set1={1,2,3}
set2={1,2,3,4,5}
print(set1.issubset(set2))

True


In [4]:
text="in this tutorial we disscusing about sets we"
words=text.split()
set(words)

{'about', 'disscusing', 'in', 'sets', 'this', 'tutorial', 'we'}

In [5]:
text="in this tutorial we disscusing about sets"
words=text.split()
unique_words = set(words)
print(unique_words)
print(len(unique_words))


{'about', 'sets', 'we', 'disscusing', 'this', 'in', 'tutorial'}
7


In [13]:
number=tuple([1,2,3,4,5,6])
number

(1, 2, 3, 4, 5, 6)

In [8]:
mixed_tuples=(1,2,"taruna",True)
print(mixed_tuples[::-1])

(True, 'taruna', 2, 1)


In [13]:
number=(1,2,3,4)
taruna=number+mixed_tuples
print(taruna)


(1, 2, 3, 4, 1, 2, 'taruna', True)


In [8]:
set1=("my ne is taruna is")
words= set1.split()

print(words)

['my', 'ne', 'is', 'taruna', 'is']


In [9]:
number1=tuple([1,2,3])
number1*3

(1, 2, 3, 1, 2, 3, 1, 2, 3)

In [12]:
lst=[1,2,3,4]
print(lst)
lst[1]="krish"
print(lst)

[1, 2, 3, 4]
[1, 'krish', 3, 4]


In [16]:
number1


(1, 2, 3)

In [23]:
print(number1.count(2))

1


In [26]:
number2=([1,2,3,4,3])
print(number2.index(3))

2


In [31]:
a,b,c,d,e=number2
print(e)

3


In [34]:
lst2=[1,2,3,4],[5,6,7],["hello"]
lst[0]

1

In [38]:
students={"name":"taruna","age":32}


In [42]:
first_tuple=(1,2,3,4)
print(type(first_tuple))

<class 'tuple'>


In [44]:
print(students['name'])

taruna


In [1]:
taru={"name":"taruna","age":32}
print(taru["name"])

taruna


In [7]:
taru["age"]=33
print(taru)
taru["address"]="India"
print(taru)

{'name': 'taruna', 'age': 33}
{'name': 'taruna', 'age': 33, 'address': 'India'}


In [15]:
del taru['address']
print(taru)

{}


In [25]:
keys=taru.values()
print(keys)

dict_values([])


In [24]:
tush={"name":"taruna","age":34}
keys=tush.items()
print(keys)

dict_items([('name', 'taruna'), ('age', 34)])


In [38]:
tush_copy1=tush.copy()
print(tush_copy1)

{'name': 'teen', 'age': 34}


In [37]:
tush["name"]="teen"
print(tush)

{'name': 'teen', 'age': 34}


In [45]:
for values in tush_copy1:
    print(keys)

dict_keys(['name', 'age'])
dict_keys(['name', 'age'])


In [42]:
keys=tush_copy1.keys()
print(keys)

dict_keys(['name', 'age'])


In [6]:
teaching={
    "teaching1":{"name":"tary","age":32},
    "teaching2":{"name":"peter","age":64}
}
print(teaching)    
    


{'teaching1': {'name': 'tary', 'age': 32}, 'teaching2': {'name': 'peter', 'age': 64}}


In [1]:
def function_name(parameters):
    """docstring"""
    #function body
    return expression


In [2]:
def even_odd(num):
    """this function performs even or odd"""
    if num%2==0:
        print("the number is even")
    else:
        print("the numver is odd")    
        

In [3]:
even_odd(24)

the number is even


In [9]:
## function with multiple parameters
def add(a,b):
    """this is adding funciton"""
    return(a+b)
add(4,8)

12

In [14]:
#default parameters
def greet(name="guest"):
    print(f"hello {name}")
greet()    

hello guest


In [15]:
##varial length arguments
def print_numbers(*krish):
    for numbers in krish:
        print(numbers)


In [17]:
print_numbers(1,2,3,4,5)

1
2
3
4
5


In [32]:
##key words argument
def print_detail(**kwargs):
    for key,values in kwargs.items():
        print(f"{key}:{values}")

In [33]:
print_detail(name="krish",age="34",country="tenth")

name:krish
age:34
country:tenth


In [28]:
def temperature(F):
    if F in range(100):
        result=((F-32)*5/9)
        print(result)
    



In [29]:
temperature(77)

25.0


In [60]:
def calculate_cost(cart):
    total_cost=0
    for item in cart:
        total_cost=item['price']*item['quantity']
    return(total_cost)
cart=[
    {'name':'apple','price':12,'quantity':2}
]     

In [61]:
calculate_cost(cart)

24

In [65]:
x = 2

In [66]:

x += 5

In [14]:
def is_palindrome(s):
    return s==s[::-1]

In [12]:
def factorial(n):
    if n==0:
        return 1
    else:
        return n*factorial(n-1)

In [13]:
factorial(4)

24

In [15]:
is_palindrome("alla")

True

In [1]:
even= lambda num:num*2
 

In [3]:
even(14)

28

In [15]:
numbers=[1,2,3,4]
list(map(lambda x:x*2, numbers))

[2, 4, 6, 8]

In [1]:
numbers=[1,2,3,4]
even=list(filter(lambda x:x>2 and x%2==0,numbers))

In [2]:
print(even)

[4]


In [7]:
import array
arr=array.array('i')

In [8]:
print(arr)

array('i')


In [13]:
import math
print(math.sqrt(5))

2.23606797749979


In [14]:
import os
print(os.getcwd())

c:\python


In [15]:
os.mkdir('test_dir')

In [1]:
import datetime
from datetime import datetime,timedelta
now=datetime.now()
print(now)

2024-12-30 17:01:50.687292


In [2]:
a=b

NameError: name 'b' is not defined

In [8]:
try:
    print(b)
except Exception as ex:
    print(ex)    

name 'b' is not defined


In [19]:
try:
    num=int(input("number"))
    result=10/num
except  Exception as ex:
    print("this is not a valid number")    
except ZeroDivisionError as ex:
    print(ex)    

this is not a valid number


In [26]:
try:
    num=int(input("enter a number"))
    result=10/num
except ValueError as ex:
    print("not valid number")
else:
    print(f"the result is {result}")    
finally:
    print("execution is complete")        

not valid number
execution is complete


In [27]:
try:
    file=open('exercise.txt','r')
    content=file.read()
    print(content)
except FileNotFoundError:
    print("the file not foundd")
        


the file not foundd


In [33]:
## class and object
class vhicle:
    pass
audi=vhicle()
bmw=vhicle()
print(type(bmw))

<class '__main__.vhicle'>


In [51]:
class student:
    def __init__(self,name,age):
       self.name=name
       self.age=age

    def summation(self):
        return self.age*2

In [52]:
s1 = student("Taruna", 26)
s2 = student("Tushar", 27)

In [54]:
s2.summation()

54

In [50]:
print(f'{s2.name}\n{s2.age}')

Tushar
27


In [1]:
class car:
    def __init__(self,windows,doors,type):
        self.windows=windows
        self.doors=doors
        self.type=type
    def drive(self):
        print(f"the person drive the{self.type}car")    

In [5]:
car1=car(4,5,"petrol")
car2=car(5,7,"deasel")
print(car1.drive())

the person drive thepetrolcar
None


In [19]:
class point:
    def __init__(self,a,b):
        self.a=a
        self.b=b
    def __add__(self,other):
        return point(self.a*other.a,self.b*other.b)    
    def __repr__(self):
        return (f"{self.a},{self.b}")
p1=point(2,3)
p2=point(4,5)
print(p1+p2)

8,15


In [36]:
my_list=[1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [37]:
iterator=iter(my_list)
print(next(iterator))

1


In [42]:
try:
    print(next(iterator))
except StopIteration:
    print("the iterator is empty")    


the iterator is empty


In [48]:
def square(n):
    for i in range(3):
        print(i**2)

In [49]:
square(3)

0
1
4


In [47]:
for i in range(3):
    print(i)

0
1
2


In [53]:
#### generators are used to read the large files

In [58]:
def main_course(fx):
    pass
    def sub_course(fx):
        print("hi welcome to the course")
        fx()
    
    return(sub_course(fx))      

In [59]:
@main_course(fx)
def course():
    print("hello")

NameError: name 'fx' is not defined

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np
arr1=np.array([[1,2,3,4,5],[5,6,7,8,9],[9,8,7,6,5]])
print(arr1)
print(type(arr1))
print(arr1.shape)

[[1 2 3 4 5]
 [5 6 7 8 9]
 [9 8 7 6 5]]
<class 'numpy.ndarray'>
(3, 5)


In [20]:
np.arange(10,0,-1).reshape(10,1)

array([[10],
       [ 9],
       [ 8],
       [ 7],
       [ 6],
       [ 5],
       [ 4],
       [ 3],
       [ 2],
       [ 1]])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
import numpy as np

In [3]:
arr3=np.array([1,2,3,4,5])
print(np.sqrt(arr3))
print(np.log(arr3))

[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [4]:
!pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ------------ --------------------------- 3.7/11.5 MB 22.1 MB/s eta 0:00:01
   ------------------------------ --------- 8.7/11.5 MB 22.1 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 21.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
data={'a':1,'b':2,'c':3}
series=pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64


In [14]:
import pandas as pd
data={
    'Name':['taruna','harshita'],
    'age':[32,21],
    'class':[10,11]
    
}

In [19]:
df=pd.DataFrame(data)
df

Name  age  class
0    taruna   32     10
1  harshita   21     11

In [21]:
import logging
logging.basicConfig(level=logging.DEBUG)
logging.debug("this is a debug message")
logging.info("this is a info message")
logging.warning("this is a warning message")
logging.error("this is a error message")
logging.critical("this is a critical message")

DEBUG:root:this is a debug message
INFO:root:this is a info message
ERROR:root:this is a error message
CRITICAL:root:this is a critical message


In [22]:
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)